const express = require("express");
const router = express.Router();
const employerController = require("../controllers/employerController");
const { upload } = require("../middleware/imageUpload");

router.get("/current_jobs", employerController.getCurrentJobs);
router.get("/job_listings", employerController.getJobListings);
router.get("/job_listings/api/data", employerController.getJobListingsAPI);
router.get("/job_listings/new", employerController.getNewJobForm);
router.post("/job_listings/new", employerController.createJobListing);
router.get("/job_listings/edit/:jobId", employerController.getEditJobForm);
router.post("/job_listings/edit/:jobId", employerController.updateJobListing);
router.delete("/job_listings/delete/:jobId", employerController.deleteJobListing);
router.get("/job_applications", employerController.getJobApplications);
router.get("/job_applications/api/data", employerController.getJobApplicationsAPI);
router.post("/job_applications/:applicationId/accept", employerController.acceptJobApplication);
router.post("/job_applications/:applicationId/reject", employerController.rejectJobApplication);
router.get("/profile", employerController.getProfile);
router.get("/profile/edit", employerController.getEditProfile);
router.post("/profile/edit", upload.single('companyImage'), employerController.updateProfile);
router.post("/profile/upload-image", upload.single('picture'), employerController.uploadProfileImage);
router.get("/transaction_history", employerController.getTransactionHistory);
router.get("/transaction_history/details/:jobId", employerController.getTransactionDetails);
router.get("/transaction_history/milestone", employerController.getMilestone);
router.get("/previously_worked", employerController.getPreviouslyWorked);
router.get("/previously_worked/api/data", employerController.getPreviouslyWorkedAPI);
router.get("/milestones", employerController.getMilestone);
router.get("/view_profile", employerController.getViewprofile);
router.post("/milestone/:jobId/:milestoneId/pay", employerController.payMilestone);
router.get("/subscription", employerController.getSubscription);
router.post("/subscription/purchase", employerController.purchaseSubscription);
router.get("/payment", employerController.getPaymentAnimation);
router.post("/upgrade_subscription", employerController.upgradeSubscription);
router.get("/complaint/form", employerController.getComplaintForm);
router.post("/complaint/submit", employerController.submitComplaintForm);
router.post("/current_jobs/complain/:jobId", employerController.submitComplaint);

module.exports = router;